# Generated by Django 4.2.14 on 2024-07-18 08:50

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, validators=[user.models.validate_username])),
                ('email', models.EmailField(max_length=254, validators=[user.models.validate_email_not_spam])),
                ('password', models.CharField(max_length=100)),
                ('password_confirmation', models.CharField(max_length=100)),
            ],
        ),
    ]
